name: test
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  pytest:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m venv venv
          .\venv\Scripts\python.exe -m pip install -U pip
          .\venv\Scripts\python.exe -m pip install -r requirements-dev.txt
      - name: Generate fixtures
        run: .\venv\Scripts\python.exe tests/generate_test_pdfs.py
      - name: Ruff
        run: .\venv\Scripts\python.exe -m ruff check .
      - name: Pytest
        run: .\venv\Scripts\python.exe -m pytest tests/ -q --cov -m "not live"
